package com.challenge.disney;

import com.challenge.disney.modelos.*;
import com.challenge.disney.repositorios.*;
import com.challenge.disney.servicios.EmailSenderServicio;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.password.PasswordEncoder;

import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import java.time.LocalDate;
import java.util.Set;

import static org.aspectj.bridge.MessageUtil.error;


@SpringBootApplication
public class DisneyApplication {

	public static void main(String[] args) {
		SpringApplication.run(DisneyApplication.class, args);

	}
	@Autowired
	public PasswordEncoder passwordEncoder;
	@Autowired
	private EmailSenderServicio emailSenderServicio;


	@Bean
	public CommandLineRunner initData(PersonajeRepositorio personajeRepositorio, PeliculaRepositorio peliculaRepositorio, GeneroRepositorio generoRepositorio, PersonajePeliculaRepositorio personajePeliculaRepositorio, GeneroPeliculaRepositorio generoPeliculaRepositorio, UsuarioRepositorio usuarioRepositorio){
		return (args) -> {

			Usuario usuario = new Usuario("Esteban", "Fak", "esteban@gmail.com", passwordEncoder.encode("123"));
			usuarioRepositorio.save(usuario);


			Personaje personaje1=new Personaje("Cenicienta", "https://album.mediaset.es/eimg/2018/03/02/KPb7rTBoxkYWcRCz6IapJ.jpg?w=1024", "Cenicienta", 19, 50);
			Personaje personaje2=new Personaje("Dumbo", "imagen", "Dumbo", 2, 50);
			Personaje personaje3=new Personaje("Blancanieves", "imagen", "Blancanieves y los 7 enanitos", 18, 50);
			Personaje personaje4=new Personaje("Pinocho", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ1KOiGnSWbNE6TtYXEGENZ7EPOG6jZT95Ow&usqp=CAU", "Pinocho", 8, 50);
			Personaje personaje5=new Personaje("Mickey Mouse", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzvGVPi0HSj8GIDL-s7H_pK3GtOBilCZXjRw&usqp=CAU", "Fantasía", 12, 50);
			Personaje personaje6=new Personaje("Bambi", "imagen", "Bambi", 2, 50);
			Personaje personaje7=new Personaje("Alicia", "imagen", "Alicia en el país de las maravillas", 20, 50);
			Personaje personaje8=new Personaje("Peter Pan", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScU6Ay5Sc7LCex5YohqLGmXuIx4bWqJxptwA&usqp=CAU", "Peter Pan", 20, 50);
			Personaje personaje9=new Personaje("Lady", "imagen", "La dama y el vagabundo", 20, 50);
			Personaje personaje10=new Personaje("Aurora", "imagen", "La bella durmiente", 20, 50);
			Personaje personaje11=new Personaje("Pongo", "imagen", "101 dálmatas", 20, 50);
			Personaje personaje12=new Personaje("Arturo", "imagen", "La Espada en la Piedra", 20, 50);
			Personaje personaje13=new Personaje("Mowgli", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeyW3s7MSVL6LHOyqkhdOgPFXUs-YOwAo1ow&s", "El libro de la selva", 20, 50);
			Personaje personaje14=new Personaje("Marie", "imagen", "Los Aristogatos", 20, 50);
			Personaje personaje15=new Personaje("Robin Hood", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSax497yFFPd_KDap02uY-dFy47Cy1dy4iJMA&s", "Robin Hood", 20, 50);
			Personaje personaje16=new Personaje("Vixey", "imagen", "El zorro y el sabueso", 20, 50);
			Personaje personaje17=new Personaje("Elena", "imagen", "Taron y el caldero mágico", 20, 50);
			Personaje personaje18=new Personaje("Toaster", "imagen", "El tostadorcito valiente", 20, 50);
			Personaje personaje19=new Personaje("Oliver", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SeDHRJBnWOUCjqmIuHk3052qNtvdWtdOSg&usqp=CAU", "Oliver y su pandilla", 20, 50);
			Personaje personaje20=new Personaje("Ariel", "imagen", "La sirenita", 20, 50);
			Personaje personaje21=new Personaje("Rico McPato", "imagen", "PatoAventuras - La película: El tesoro de la lámpara perdida", 20, 50);
			Personaje personaje22=new Personaje("Bernardo", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBWeDPtwPKv_VfO9fNulWJpfOKJr4ifgz4kw&usqp=CAU", "Bernardo y Bianca en Cangurolandia", 20, 50);
			Personaje personaje23=new Personaje("Bella", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAkvk1bfEU28_g5V8c-bofy9RmV6f0xmiqeQ&usqp=CAU", "La bella y la bestia", 20, 50);
			Personaje personaje24=new Personaje("Aladdin", "imagen", "Aladdín", 20, 50);
			Personaje personaje25=new Personaje("Jack Skellington", "imagen", "El extraño mundo de Jack", 20, 50);
			Personaje personaje26=new Personaje("Simba", "imagen", "El rey león", 20, 50);
			Personaje personaje27=new Personaje("Goofy", "imagen", "Goofy, la película", 20, 50);
			Personaje personaje28=new Personaje("Pocahontas", "imagen", "Pocahontas", 20, 50);
			Personaje personaje29=new Personaje("Woody", "imagen", "Toy Story", 20, 50);
			Personaje personaje30=new Personaje("James", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmTIFibJS5Ob8xbKmt7rkFIX49SIEPp6_0_Q&usqp=CAU", "James y el melocotón gigante", 20, 50);
			Personaje personaje31=new Personaje("Quasimodo", "imagen", "El jorobado de Notre Dame", 20, 50);
			Personaje personaje32=new Personaje("Hercules", "imagen", "Hércules", 20, 50);
			Personaje personaje33=new Personaje("Mulan", "imagen", "Mulán", 20, 50);
			Personaje personaje34=new Personaje("Flik", "imagen", "Bichos: Una aventura en miniatura", 20, 50);
			Personaje personaje35=new Personaje("Tarzan", "imagen", "Tarzán", 20, 50);
			Personaje personaje36=new Personaje("Kronk", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ13seMmpm-GzpbEIxUm7-l5GxdLSf0Js4TquDp64OXSaI&s=10", "Las locuras del emperador", 20, 50);
			Personaje personaje37=new Personaje("Milo James Thatch", "imagen", "Atlantis: El imperio perdido", 20, 50);
			Personaje personaje38=new Personaje("James Sullivan", "imagen", "Monsters, Inc.", 20, 50);
			Personaje personaje39=new Personaje("Lilo Pelekai", "imagen", "Lilo & Stitch", 20, 50);
			Personaje personaje40=new Personaje("Jim Hawkins", "imagen", "El planeta del tesoro", 20, 50);
			Personaje personaje41=new Personaje("Nemo", "imagen", "Buscando a Nemo", 20, 50);
			Personaje personaje42=new Personaje("Koda", "imagen", "Tierra de osos", 20, 50);
			Personaje personaje43=new Personaje("Grace", "imagen", "Vacas Vaqueras", 20, 50);
			Personaje personaje44=new Personaje("Robert Bob Parr", "imagen", "Los Increíbles", 20, 50);
			Personaje personaje45=new Personaje("Rayo McQueen", "imagen", "Cars", 20, 50);
			Personaje personaje46=new Personaje("Lewis", "imagen", "La Familia del Futuro", 20, 50);
			Personaje personaje47=new Personaje("Alfredo Linguini", "imagen", "Ratatouille", 20, 50);
			Personaje personaje48=new Personaje("Wall-E", "imagen", "WALL·E", 20, 50);
			Personaje personaje49=new Personaje("Bolt", "imagen", "Bolt: Un Perro fuera de serie", 20, 50);
			Personaje personaje50=new Personaje("Russell", "imagen", "Up: Una Aventura de Altura", 20, 50);
			Personaje personaje51=new Personaje("Tiana", "imagen", "La princesa y el sapo", 20, 50);
			Personaje personaje52=new Personaje("Rapunzel", "imagen", "Enredados", 20, 50);
			Personaje personaje53=new Personaje("Victor Frankenstein", "imagen", "Frankenweenie", 20, 50);
			Personaje personaje54=new Personaje("Princesa Merida", "imagen", "Valiente", 20, 50);
			Personaje personaje55=new Personaje("Ralph", "imagen", "Ralph el demoledor", 20, 50);
			Personaje personaje56=new Personaje("Elsa", "imagen", "Frozen: Una Aventura Congelada", 20, 50);
			Personaje personaje57=new Personaje("Hiro Hamada", "imagen", "Grandes Héroes", 20, 50);
			Personaje personaje58=new Personaje("Alegria", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbvllpaSDhfeJAgg1zw9GlAJOI0oqL5czhwsGbQYo-ZfU&s=10", "Intensamente", 20, 50);
			Personaje personaje59=new Personaje("Arlo", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOIwbwzRNbaUtnNRCUOZqWMmfyf9GBREfNn8yrOMoGQu8&s=10", "Un Gran Dinosaurio", 20, 50);
			Personaje personaje60=new Personaje("Judy Hopps", "imagen", "Zootopia", 20, 50);
			Personaje personaje61=new Personaje("Moana", "imagen", "Moana", 20, 50);
			Personaje personaje62=new Personaje("Miguel", "imagen", "Coco", 20, 50);
			Personaje personaje63=new Personaje("Ian Lightfoot", "imagen", "Unidos", 20, 50);
			Personaje personaje64=new Personaje("Joe Gardner", "imagen", "Soul", 20, 50);
			Personaje personaje65=new Personaje("Mirabel Madrigal", "imagen", "Encanto", 20, 50);
			Personaje personaje66=new Personaje("Meilin Lee", "imagen", "Turning Red", 20, 50);



			personajeRepositorio.save(personaje1);
			personajeRepositorio.save(personaje2);
			personajeRepositorio.save(personaje3);
			personajeRepositorio.save(personaje4);
			personajeRepositorio.save(personaje5);
			personajeRepositorio.save(personaje6);
			personajeRepositorio.save(personaje7);
			personajeRepositorio.save(personaje8);
			personajeRepositorio.save(personaje9);
			personajeRepositorio.save(personaje10);
			personajeRepositorio.save(personaje11);
			personajeRepositorio.save(personaje12);
			personajeRepositorio.save(personaje13);
			personajeRepositorio.save(personaje14);
			personajeRepositorio.save(personaje15);
			personajeRepositorio.save(personaje16);
			personajeRepositorio.save(personaje17);
			personajeRepositorio.save(personaje18);
			personajeRepositorio.save(personaje19);
			personajeRepositorio.save(personaje20);
			personajeRepositorio.save(personaje21);
			personajeRepositorio.save(personaje22);
			personajeRepositorio.save(personaje23);
			personajeRepositorio.save(personaje24);
			personajeRepositorio.save(personaje25);
			personajeRepositorio.save(personaje26);
			personajeRepositorio.save(personaje27);
			personajeRepositorio.save(personaje28);
			personajeRepositorio.save(personaje29);
			personajeRepositorio.save(personaje30);
			personajeRepositorio.save(personaje31);
			personajeRepositorio.save(personaje32);
			personajeRepositorio.save(personaje33);
			personajeRepositorio.save(personaje34);
			personajeRepositorio.save(personaje35);
			personajeRepositorio.save(personaje36);
			personajeRepositorio.save(personaje37);
			personajeRepositorio.save(personaje38);
			personajeRepositorio.save(personaje39);
			personajeRepositorio.save(personaje40);
			personajeRepositorio.save(personaje41);
			personajeRepositorio.save(personaje42);
			personajeRepositorio.save(personaje43);
			personajeRepositorio.save(personaje44);
			personajeRepositorio.save(personaje45);
			personajeRepositorio.save(personaje46);
			personajeRepositorio.save(personaje47);
			personajeRepositorio.save(personaje48);
			personajeRepositorio.save(personaje49);
			personajeRepositorio.save(personaje50);
			personajeRepositorio.save(personaje51);
			personajeRepositorio.save(personaje52);
			personajeRepositorio.save(personaje53);
			personajeRepositorio.save(personaje54);
			personajeRepositorio.save(personaje55);
			personajeRepositorio.save(personaje56);
			personajeRepositorio.save(personaje57);
			personajeRepositorio.save(personaje58);
			personajeRepositorio.save(personaje59);
			personajeRepositorio.save(personaje60);
			personajeRepositorio.save(personaje61);
			personajeRepositorio.save(personaje62);
			personajeRepositorio.save(personaje63);
			personajeRepositorio.save(personaje64);
			personajeRepositorio.save(personaje65);
			personajeRepositorio.save(personaje66);


			Pelicula pelicula1 = new Pelicula("https://cdn.superaficionados.com/imagenes/68-mejores-peliculas-disney-cenicienta-cke.jpg", "Cenicienta", 1950, (byte) 5);
			Pelicula pelicula5 = new Pelicula("https://cdn.superaficionados.com/imagenes/70-mejores-peliculas-disney-dumbo-cke.jpg", "Dumbo", 1941, (byte) 2);
			Pelicula pelicula6 = new Pelicula("https://www.latercera.com/resizer/KNCurPMFYgdkmSSbtv-PxZ9rsJE=/900x600/smart/arc-anglerfish-arc2-prod-copesa.s3.amazonaws.com/public/7RFRE26H6RCTXDDZC73G3RTXC4.jpg", "Blancanieves y los 7 enanitos", 1937, (byte) 2);
			Pelicula pelicula7 = new Pelicula("https://cdn.superaficionados.com/imagenes/72-mejores-peliculas-disney-pinocho-cke.jpg", "Pinocho", 1940, (byte) 4);
			Pelicula pelicula8 = new Pelicula("https://cdn.superaficionados.com/imagenes/71-mejores-peliculas-disney-fantasia-1-cke.jpg", "Fantasía", 1996, (byte) 2);
			Pelicula pelicula9= new Pelicula("https://cdn.superaficionados.com/imagenes/69-mejores-peliculas-disney-bambi-cke.jpg", "Bambi", 1942, (byte) 5);
			Pelicula pelicula10= new Pelicula("https://cdn.superaficionados.com/imagenes/67-mejores-peliculas-disney-alicia-en-el-pais-de-las-maravillas-cke.jpg", "Alicia en el país de las maravillas", 1951, (byte) 5);
			Pelicula pelicula11= new Pelicula("https://cdn.superaficionados.com/imagenes/66-mejores-peliculas-disney-peter-pan-cke.jpg", "Peter Pan", 1953, (byte) 5);
			Pelicula pelicula12= new Pelicula("https://cdn.superaficionados.com/imagenes/65-mejores-peliculas-disney-la-dama-y-el-vagabundo-cke.jpg", "La dama y el vagabundo", 1955, (byte) 5);
			Pelicula pelicula13= new Pelicula("https://cdn.superaficionados.com/imagenes/64-mejores-peliculas-disney-la-bella-durmiente-cke.jpg", "La bella durmiente", 1959, (byte) 5);
			Pelicula pelicula14= new Pelicula("https://cdn.superaficionados.com/imagenes/63-mejores-peliculas-disney-101-dalmatas-cke.jpg", "101 dálmatas", 1961, (byte) 5);
			Pelicula pelicula15= new Pelicula("https://cdn.superaficionados.com/imagenes/62-mejores-peliculas-disney-la-espada-en-la-piedra.jpg", "La Espada en la Piedra", 1963, (byte) 5);
			Pelicula pelicula16= new Pelicula("https://cdn.superaficionados.com/imagenes/60-mejores-peliculas-disney-el-libro-de-la-selva-cke.jpg", "El libro de la selva", 1967, (byte) 5);
			Pelicula pelicula17= new Pelicula("https://cdn.superaficionados.com/imagenes/59-mejores-peliculas-disney-los-aristogatos-cke.jpg", "Los Aristogatos", 1970, (byte) 5);
			Pelicula pelicula18= new Pelicula("https://cdn.superaficionados.com/imagenes/58-mejores-peliculas-disney-robin-hood-cke.jpg", "Robin Hood", 1973, (byte) 5);
			Pelicula pelicula19= new Pelicula("https://cdn.superaficionados.com/imagenes/57-mejores-peliculas-disney-el-zorro-y-el-sabueso-cke.jpg", "El zorro y el sabueso", 1981, (byte) 5);
			Pelicula pelicula20= new Pelicula("https://cdn.superaficionados.com/imagenes/56-mejores-peliculas-disney-taron-y-el-caldero-magico-cke.jpg", "Taron y el caldero mágico", 1985, (byte) 5);
			Pelicula pelicula21= new Pelicula("https://cdn.superaficionados.com/imagenes/55-mejores-peliculas-disney-el-tostadorcito-valiente-cke.jpg", "El tostadorcito valiente", 1987, (byte) 5);
			Pelicula pelicula22= new Pelicula("https://cdn.superaficionados.com/imagenes/54-mejores-peliculas-disney-oliver-y-su-pandilla-cke.jpg", "Oliver y su pandilla", 1988, (byte) 5);
			Pelicula pelicula23= new Pelicula("https://cdn.superaficionados.com/imagenes/53-mejores-peliculas-disney-la-sirenita-cke.jpg", "La sirenita", 1989, (byte) 5);
			Pelicula pelicula24= new Pelicula("https://cdn.superaficionados.com/imagenes/52-mejores-peliculas-disney-patoaventuras-la-pelicula-el-tesoro-de-la-lampara-perdida-cke.jpg", "PatoAventuras - La película: El tesoro de la lámpara perdida", 1990, (byte) 5);
			Pelicula pelicula25= new Pelicula("https://cdn.superaficionados.com/imagenes/51-mejores-peliculas-disney-bernardo-y-bianca-en-cangurolandia-cke.jpg", "Bernardo y Bianca en Cangurolandia", 1990, (byte) 5);
			Pelicula pelicula26= new Pelicula("https://cdn.superaficionados.com/imagenes/50-mejores-peliculas-disney-la-bella-y-la-bestia-cke.jpg", "La bella y la bestia", 1991, (byte) 5);
			Pelicula pelicula27= new Pelicula("https://cdn.superaficionados.com/imagenes/49-mejores-peliculas-disney-aladdin-cke.jpg", "Aladdín", 1992, (byte) 5);
			Pelicula pelicula28= new Pelicula("https://cdn.superaficionados.com/imagenes/46-mejores-peliculas-disney-el-extrano-mundo-de-jack-cke.jpg", "El extraño mundo de Jack", 1993, (byte) 5);
			Pelicula pelicula29= new Pelicula("https://cdn.superaficionados.com/imagenes/45-mejores-peliculas-disney-el-rey-leon-cke.jpg", "El rey león", 1994, (byte) 5);
			Pelicula pelicula30= new Pelicula("https://cdn.superaficionados.com/imagenes/44-mejores-peliculas-disney-goofy-la-pelicula-cke.jpg", "Goofy, la película", 1995, (byte) 5);
			Pelicula pelicula31= new Pelicula("https://cdn.superaficionados.com/imagenes/43-mejores-peliculas-disney-pocahontas-cke.jpg", "Pocahontas", 1995, (byte) 5);
			Pelicula pelicula32= new Pelicula("https://cdn.superaficionados.com/imagenes/42-mejores-peliculas-disney-toy-story-cke.jpg", "Toy Story", 1995, (byte) 5);
			Pelicula pelicula33= new Pelicula("https://cdn.superaficionados.com/imagenes/41-mejores-peliculas-disney-james-y-el-melocoton-gigante-cke.jpg", "James y el melocotón gigante", 1996, (byte) 5);
			Pelicula pelicula34= new Pelicula("https://cdn.superaficionados.com/imagenes/40-mejores-peliculas-disney-el-jorobado-de-notre-dame-cke.jpg", "El jorobado de Notre Dame", 1996, (byte) 5);
			Pelicula pelicula35= new Pelicula("https://cdn.superaficionados.com/imagenes/39-mejores-peliculas-disney-hercules-cke.jpg", "Hércules", 1997, (byte) 5);
			Pelicula pelicula36= new Pelicula("https://cdn.superaficionados.com/imagenes/36-mejores-peliculas-disney-mulan-cke.jpg", "Mulán", 1998, (byte) 5);
			Pelicula pelicula37= new Pelicula("https://cdn.superaficionados.com/imagenes/35-mejores-peliculas-disney-bichos-una-aventura-en-miniatura-cke.jpg", "Bichos: Una aventura en miniatura", 1998, (byte) 5);
			Pelicula pelicula38= new Pelicula("https://cdn.superaficionados.com/imagenes/34-mejores-peliculas-disney-tarzan-cke.jpg", "Tarzán", 1999, (byte) 5);
			Pelicula pelicula39= new Pelicula("https://cdn.superaficionados.com/imagenes/33-mejores-peliculas-disney-las-locuras-del-emperador-cke.jpg", "Las locuras del emperador", 2000, (byte) 5);
			Pelicula pelicula40= new Pelicula("https://cdn.superaficionados.com/imagenes/32-mejores-peliculas-disney-atlantis-el-imperio-perdido-0-cke.jpg", "Atlantis: El imperio perdido", 2001, (byte) 5);
			Pelicula pelicula41= new Pelicula("https://cdn.superaficionados.com/imagenes/30-mejores-peliculas-disney-monsters-inc-cke.jpg", "Monsters, Inc.", 2001, (byte) 5);
			Pelicula pelicula42= new Pelicula("https://cdn.superaficionados.com/imagenes/29-mejores-peliculas-disney-lilo-stitch-cke.jpg", "Lilo & Stitch", 2002, (byte) 5);
			Pelicula pelicula43= new Pelicula("https://cdn.superaficionados.com/imagenes/28-mejores-peliculas-disney-el-planeta-del-tesoro-cke.jpg", "El planeta del tesoro", 2002, (byte) 5);
			Pelicula pelicula44= new Pelicula("https://cdn.superaficionados.com/imagenes/27-mejores-peliculas-disney-buscando-a-nemo-cke.jpg", "Buscando a Nemo", 2003, (byte) 5);
			Pelicula pelicula45= new Pelicula("https://cdn.superaficionados.com/imagenes/25-mejores-peliculas-disney-tierra-de-osos-cke.jpg", "Tierra de osos", 2003, (byte) 5);
			Pelicula pelicula46= new Pelicula("https://cdn.superaficionados.com/imagenes/24-mejores-peliculas-disney-vacas-vaqueras-cke.jpg", "Vacas Vaqueras", 2004, (byte) 5);
			Pelicula pelicula47= new Pelicula("https://cdn.superaficionados.com/imagenes/23-mejores-peliculas-disney-los-increibles-cke.jpg", "Los Increíbles", 2004, (byte) 5);
			Pelicula pelicula48= new Pelicula("https://cdn.superaficionados.com/imagenes/22-mejores-peliculas-disney-cars-cke.jpg", "Cars", 2006, (byte) 5);
			Pelicula pelicula49= new Pelicula("https://cdn.superaficionados.com/imagenes/21-mejores-peliculas-disney-la-familia-del-futuro-cke.jpg", "La Familia del Futuro", 2007, (byte) 5);
			Pelicula pelicula50= new Pelicula("https://cdn.superaficionados.com/imagenes/20-mejores-peliculas-disney-ratatouille-cke.jpg", "Ratatouille", 2007, (byte) 5);
			Pelicula pelicula51= new Pelicula("https://cdn.superaficionados.com/imagenes/19-mejores-peliculas-disney-wall-e-cke.jpg", "WALL·E", 2008, (byte) 5);
			Pelicula pelicula52= new Pelicula("https://cdn.superaficionados.com/imagenes/18-mejores-peliculas-disney-bolt-un-perro-fuera-de-serie-cke.jpg", "Bolt: Un Perro fuera de serie", 2008, (byte) 5);
			Pelicula pelicula53= new Pelicula("https://cdn.superaficionados.com/imagenes/17-mejores-peliculas-disney-up-una-aventura-de-altura-cke.jpg", "Up: Una Aventura de Altura", 2009, (byte) 5);
			Pelicula pelicula54= new Pelicula("https://cdn.superaficionados.com/imagenes/16-mejores-peliculas-disney-la-princesa-y-el-sapo-cke.jpg", "La princesa y el sapo", 2009, (byte) 5);
			Pelicula pelicula55= new Pelicula("https://cdn.superaficionados.com/imagenes/15-mejores-peliculas-disney-enredados-cke.jpg", "Enredados", 2010, (byte) 5);
			Pelicula pelicula56= new Pelicula("https://cdn.superaficionados.com/imagenes/13-mejores-peliculas-disney-frankenweenie-cke.jpg", "Frankenweenie", 2012, (byte) 5);
			Pelicula pelicula57= new Pelicula("https://cdn.superaficionados.com/imagenes/12-mejores-peliculas-disney-valiente-cke.jpg", "Valiente", 2012, (byte) 5);
			Pelicula pelicula58= new Pelicula("https://cdn.superaficionados.com/imagenes/11-mejores-peliculas-disney-ralph-el-demoledor-cke.jpg", "Ralph el demoledor", 2012, (byte) 5);
			Pelicula pelicula59= new Pelicula("https://cdn.superaficionados.com/imagenes/10-mejores-peliculas-disney-frozen-cke.jpg", "Frozen: Una Aventura Congelada", 2013, (byte) 5);
			Pelicula pelicula60= new Pelicula("https://cdn.superaficionados.com/imagenes/9-mejores-peliculas-disney-grandes-heroes-cke.jpg", "Grandes Héroes", 2014, (byte) 5);
			Pelicula pelicula61= new Pelicula("https://cdn.superaficionados.com/imagenes/8-mejores-peliculas-disney-intensamente-cke.jpg", "Intensamente", 2015, (byte) 5);
			Pelicula pelicula62= new Pelicula("https://cdn.superaficionados.com/imagenes/7-mejores-peliculas-disney-un-gran-dinosaurio-cke.jpg", "Un Gran Dinosaurio", 2015, (byte) 5);
			Pelicula pelicula63= new Pelicula("https://cdn.superaficionados.com/imagenes/6-mejores-peliculas-disney-zootopia-0-cke.jpg", "Zootopia", 2016, (byte) 5);
			Pelicula pelicula64= new Pelicula("https://cdn.superaficionados.com/imagenes/4-mejores-peliculas-disney-moana-0-cke.jpg", "Moana", 2016, (byte) 5);
			Pelicula pelicula65= new Pelicula("https://cdn.superaficionados.com/imagenes/3-mejores-peliculas-disney-coco-cke.jpg", "Coco", 2017, (byte) 5);
			Pelicula pelicula66= new Pelicula("https://cdn.superaficionados.com/imagenes/1-mejores-peliculas-disney-onward-cke.jpg", "Unidos", 2020, (byte) 5);
			Pelicula pelicula67= new Pelicula("https://cdn.superaficionados.com/imagenes/3-peliculas-de-disney-soul-cke.jpg", "Soul", 2020, (byte) 5);
			Pelicula pelicula68= new Pelicula("https://cdn.superaficionados.com/imagenes/2-peliculas-de-disney-encanto.jpg", "Encanto", 2022, (byte) 5);
			Pelicula pelicula69= new Pelicula("https://cdn.superaficionados.com/imagenes/1-peliculas-de-disney-turning-red-cke.jpg", "Turning Red", 2022, (byte) 5);


			peliculaRepositorio.save(pelicula1);
			peliculaRepositorio.save(pelicula5);
			peliculaRepositorio.save(pelicula6);
			peliculaRepositorio.save(pelicula7);
			peliculaRepositorio.save(pelicula8);
			peliculaRepositorio.save(pelicula9);
			peliculaRepositorio.save(pelicula10);
			peliculaRepositorio.save(pelicula11);
			peliculaRepositorio.save(pelicula12);
			peliculaRepositorio.save(pelicula13);
			peliculaRepositorio.save(pelicula14);
			peliculaRepositorio.save(pelicula15);
			peliculaRepositorio.save(pelicula16);
			peliculaRepositorio.save(pelicula17);
			peliculaRepositorio.save(pelicula18);
			peliculaRepositorio.save(pelicula19);
			peliculaRepositorio.save(pelicula20);
			peliculaRepositorio.save(pelicula21);
			peliculaRepositorio.save(pelicula22);
			peliculaRepositorio.save(pelicula23);
			peliculaRepositorio.save(pelicula24);
			peliculaRepositorio.save(pelicula25);
			peliculaRepositorio.save(pelicula26);
			peliculaRepositorio.save(pelicula27);
			peliculaRepositorio.save(pelicula28);
			peliculaRepositorio.save(pelicula29);
			peliculaRepositorio.save(pelicula30);
			peliculaRepositorio.save(pelicula31);
			peliculaRepositorio.save(pelicula32);
			peliculaRepositorio.save(pelicula33);
			peliculaRepositorio.save(pelicula34);
			peliculaRepositorio.save(pelicula35);
			peliculaRepositorio.save(pelicula36);
			peliculaRepositorio.save(pelicula37);
			peliculaRepositorio.save(pelicula38);
			peliculaRepositorio.save(pelicula39);
			peliculaRepositorio.save(pelicula40);
			peliculaRepositorio.save(pelicula41);
			peliculaRepositorio.save(pelicula42);
			peliculaRepositorio.save(pelicula43);
			peliculaRepositorio.save(pelicula44);
			peliculaRepositorio.save(pelicula45);
			peliculaRepositorio.save(pelicula46);
			peliculaRepositorio.save(pelicula47);
			peliculaRepositorio.save(pelicula48);
			peliculaRepositorio.save(pelicula49);
			peliculaRepositorio.save(pelicula50);
			peliculaRepositorio.save(pelicula51);
			peliculaRepositorio.save(pelicula52);
			peliculaRepositorio.save(pelicula53);
			peliculaRepositorio.save(pelicula54);
			peliculaRepositorio.save(pelicula55);
			peliculaRepositorio.save(pelicula56);
			peliculaRepositorio.save(pelicula57);
			peliculaRepositorio.save(pelicula58);
			peliculaRepositorio.save(pelicula59);
			peliculaRepositorio.save(pelicula60);
			peliculaRepositorio.save(pelicula61);
			peliculaRepositorio.save(pelicula62);
			peliculaRepositorio.save(pelicula63);
			peliculaRepositorio.save(pelicula64);
			peliculaRepositorio.save(pelicula65);
			peliculaRepositorio.save(pelicula66);
			peliculaRepositorio.save(pelicula67);
			peliculaRepositorio.save(pelicula68);
			peliculaRepositorio.save(pelicula69);


			Genero genero1 = new Genero("Fantasia", "https://cdn.superaficionados.com/imagenes/73-mejores-peliculas-disney-blancanieves-y-los-siete-enanitos-cke.jpg");
			Genero genero2 = new Genero("Acción", "https://cdn.superaficionados.com/imagenes/56-mejores-peliculas-disney-taron-y-el-caldero-magico-cke.jpg");
			Genero genero3 = new Genero("Crimen", "https://i.pinimg.com/originals/c8/90/3a/c8903a50d60bc3903e0f6dd8b0dd9510.jpg");
			Genero genero4 = new Genero("Animación", "https://2.bp.blogspot.com/-oPXopoW1Crc/WPpFA5AHAOI/AAAAAAAAD9c/D7FlA93gWVc1yY9Sv5vP0iQGsFP6RdXgACLcB/s400/walt-disney-company.jpeg");
			Genero genero5 = new Genero("Aventura", "https://cdn.superaficionados.com/imagenes/15-mejores-peliculas-disney-enredados-cke.jpg");
			Genero genero6 = new Genero("Comedia", "https://cdn.superaficionados.com/imagenes/6-mejores-peliculas-disney-zootopia-0-cke.jpg");
			Genero genero7 = new Genero("Musical", "https://www.rankuzz.com/images/2/3/1/los_mejores_musicales_de_disney_132_portada.png");
			Genero genero8 = new Genero("Familiar", "https://www.lanacion.com.py/resizer/OrULD8YbSIIE8jCjdd1Qt2MpwIY=/fit-in/1000x800/smart/cloudfront-us-east-1.images.arcpublishing.com/lanacionpy/7YQRCY4CTBHENOWINSVGUPKT6U.jpeg");
			Genero genero9 = new Genero("Drama", "image");
			generoRepositorio.save(genero1);
			generoRepositorio.save(genero2);
			generoRepositorio.save(genero3);
			generoRepositorio.save(genero4);
			generoRepositorio.save(genero5);
			generoRepositorio.save(genero6);
			generoRepositorio.save(genero7);
			generoRepositorio.save(genero8);
			generoRepositorio.save(genero9);


			PersonajePelicula personajePelicula1=new PersonajePelicula(pelicula1, personaje1);
			PersonajePelicula personajePelicula2=new PersonajePelicula(pelicula5, personaje2);
			PersonajePelicula personajePelicula3=new PersonajePelicula(pelicula6, personaje3);
			PersonajePelicula personajePelicula4=new PersonajePelicula(pelicula7, personaje4);
			PersonajePelicula personajePelicula5=new PersonajePelicula(pelicula8, personaje5);
			PersonajePelicula personajePelicula6=new PersonajePelicula(pelicula9, personaje6);
			PersonajePelicula personajePelicula7=new PersonajePelicula(pelicula10, personaje7);
			PersonajePelicula personajePelicula8=new PersonajePelicula(pelicula11, personaje8);
			PersonajePelicula personajePelicula9=new PersonajePelicula(pelicula12, personaje9);
			PersonajePelicula personajePelicula10=new PersonajePelicula(pelicula13, personaje10);
			PersonajePelicula personajePelicula11=new PersonajePelicula(pelicula14, personaje11);
			PersonajePelicula personajePelicula12=new PersonajePelicula(pelicula15, personaje12);
			PersonajePelicula personajePelicula13=new PersonajePelicula(pelicula16, personaje13);
			PersonajePelicula personajePelicula14=new PersonajePelicula(pelicula17, personaje14);
			PersonajePelicula personajePelicula15=new PersonajePelicula(pelicula18, personaje15);
			PersonajePelicula personajePelicula16=new PersonajePelicula(pelicula19, personaje16);
			PersonajePelicula personajePelicula17=new PersonajePelicula(pelicula20, personaje17);
			PersonajePelicula personajePelicula18=new PersonajePelicula(pelicula21, personaje18);
			PersonajePelicula personajePelicula19=new PersonajePelicula(pelicula22, personaje19);
			PersonajePelicula personajePelicula20=new PersonajePelicula(pelicula23, personaje20);
			PersonajePelicula personajePelicula21=new PersonajePelicula(pelicula24, personaje21);
			PersonajePelicula personajePelicula22=new PersonajePelicula(pelicula25, personaje22);
			PersonajePelicula personajePelicula23=new PersonajePelicula(pelicula26, personaje23);
			PersonajePelicula personajePelicula24=new PersonajePelicula(pelicula27, personaje24);
			PersonajePelicula personajePelicula25=new PersonajePelicula(pelicula28, personaje25);
			PersonajePelicula personajePelicula26=new PersonajePelicula(pelicula29, personaje26);
			PersonajePelicula personajePelicula27=new PersonajePelicula(pelicula30, personaje27);
			PersonajePelicula personajePelicula28=new PersonajePelicula(pelicula31, personaje28);
			PersonajePelicula personajePelicula29=new PersonajePelicula(pelicula32, personaje29);
			PersonajePelicula personajePelicula30=new PersonajePelicula(pelicula33, personaje30);
			PersonajePelicula personajePelicula31=new PersonajePelicula(pelicula34, personaje31);
			PersonajePelicula personajePelicula32=new PersonajePelicula(pelicula35, personaje32);
			PersonajePelicula personajePelicula33=new PersonajePelicula(pelicula36, personaje33);
			PersonajePelicula personajePelicula34=new PersonajePelicula(pelicula37, personaje34);
			PersonajePelicula personajePelicula35=new PersonajePelicula(pelicula38, personaje35);
			PersonajePelicula personajePelicula36=new PersonajePelicula(pelicula39, personaje36);
			PersonajePelicula personajePelicula37=new PersonajePelicula(pelicula40, personaje37);
			PersonajePelicula personajePelicula38=new PersonajePelicula(pelicula41, personaje38);
			PersonajePelicula personajePelicula39=new PersonajePelicula(pelicula42, personaje39);
			PersonajePelicula personajePelicula40=new PersonajePelicula(pelicula43, personaje40);
			PersonajePelicula personajePelicula41=new PersonajePelicula(pelicula44, personaje41);
			PersonajePelicula personajePelicula42=new PersonajePelicula(pelicula45, personaje42);
			PersonajePelicula personajePelicula43=new PersonajePelicula(pelicula46, personaje43);
			PersonajePelicula personajePelicula44=new PersonajePelicula(pelicula47, personaje44);
			PersonajePelicula personajePelicula45=new PersonajePelicula(pelicula48, personaje45);
			PersonajePelicula personajePelicula46=new PersonajePelicula(pelicula49, personaje46);
			PersonajePelicula personajePelicula47=new PersonajePelicula(pelicula50, personaje47);
			PersonajePelicula personajePelicula48=new PersonajePelicula(pelicula51, personaje48);
			PersonajePelicula personajePelicula49=new PersonajePelicula(pelicula52, personaje49);
			PersonajePelicula personajePelicula50=new PersonajePelicula(pelicula53, personaje50);
			PersonajePelicula personajePelicula51=new PersonajePelicula(pelicula54, personaje51);
			PersonajePelicula personajePelicula52=new PersonajePelicula(pelicula55, personaje52);
			PersonajePelicula personajePelicula53=new PersonajePelicula(pelicula56, personaje53);
			PersonajePelicula personajePelicula54=new PersonajePelicula(pelicula57, personaje54);
			PersonajePelicula personajePelicula55=new PersonajePelicula(pelicula58, personaje55);
			PersonajePelicula personajePelicula56=new PersonajePelicula(pelicula59, personaje56);
			PersonajePelicula personajePelicula57=new PersonajePelicula(pelicula60, personaje57);
			PersonajePelicula personajePelicula58=new PersonajePelicula(pelicula61, personaje58);
			PersonajePelicula personajePelicula59=new PersonajePelicula(pelicula62, personaje59);
			PersonajePelicula personajePelicula60=new PersonajePelicula(pelicula63, personaje60);
			PersonajePelicula personajePelicula61=new PersonajePelicula(pelicula64, personaje61);
			PersonajePelicula personajePelicula62=new PersonajePelicula(pelicula65, personaje62);
			PersonajePelicula personajePelicula63=new PersonajePelicula(pelicula66, personaje63);
			PersonajePelicula personajePelicula64=new PersonajePelicula(pelicula67, personaje64);
			PersonajePelicula personajePelicula65=new PersonajePelicula(pelicula68, personaje65);
			PersonajePelicula personajePelicula66=new PersonajePelicula(pelicula69, personaje66);
			personajePeliculaRepositorio.save(personajePelicula1);
			personajePeliculaRepositorio.save(personajePelicula2);
			personajePeliculaRepositorio.save(personajePelicula3);
			personajePeliculaRepositorio.save(personajePelicula4);
			personajePeliculaRepositorio.save(personajePelicula5);
			personajePeliculaRepositorio.save(personajePelicula6);
			personajePeliculaRepositorio.save(personajePelicula7);
			personajePeliculaRepositorio.save(personajePelicula8);
			personajePeliculaRepositorio.save(personajePelicula9);
			personajePeliculaRepositorio.save(personajePelicula10);
			personajePeliculaRepositorio.save(personajePelicula11);
			personajePeliculaRepositorio.save(personajePelicula12);
			personajePeliculaRepositorio.save(personajePelicula13);
			personajePeliculaRepositorio.save(personajePelicula14);
			personajePeliculaRepositorio.save(personajePelicula15);
			personajePeliculaRepositorio.save(personajePelicula16);
			personajePeliculaRepositorio.save(personajePelicula17);
			personajePeliculaRepositorio.save(personajePelicula18);
			personajePeliculaRepositorio.save(personajePelicula19);
			personajePeliculaRepositorio.save(personajePelicula20);
			personajePeliculaRepositorio.save(personajePelicula21);
			personajePeliculaRepositorio.save(personajePelicula22);
			personajePeliculaRepositorio.save(personajePelicula23);
			personajePeliculaRepositorio.save(personajePelicula24);
			personajePeliculaRepositorio.save(personajePelicula25);
			personajePeliculaRepositorio.save(personajePelicula26);
			personajePeliculaRepositorio.save(personajePelicula27);
			personajePeliculaRepositorio.save(personajePelicula28);
			personajePeliculaRepositorio.save(personajePelicula29);
			personajePeliculaRepositorio.save(personajePelicula30);
			personajePeliculaRepositorio.save(personajePelicula31);
			personajePeliculaRepositorio.save(personajePelicula32);
			personajePeliculaRepositorio.save(personajePelicula33);
			personajePeliculaRepositorio.save(personajePelicula34);
			personajePeliculaRepositorio.save(personajePelicula35);
			personajePeliculaRepositorio.save(personajePelicula36);
			personajePeliculaRepositorio.save(personajePelicula37);
			personajePeliculaRepositorio.save(personajePelicula38);
			personajePeliculaRepositorio.save(personajePelicula39);
			personajePeliculaRepositorio.save(personajePelicula40);
			personajePeliculaRepositorio.save(personajePelicula41);
			personajePeliculaRepositorio.save(personajePelicula42);
			personajePeliculaRepositorio.save(personajePelicula43);
			personajePeliculaRepositorio.save(personajePelicula44);
			personajePeliculaRepositorio.save(personajePelicula45);
			personajePeliculaRepositorio.save(personajePelicula46);
			personajePeliculaRepositorio.save(personajePelicula47);
			personajePeliculaRepositorio.save(personajePelicula48);
			personajePeliculaRepositorio.save(personajePelicula49);
			personajePeliculaRepositorio.save(personajePelicula50);
			personajePeliculaRepositorio.save(personajePelicula51);
			personajePeliculaRepositorio.save(personajePelicula52);
			personajePeliculaRepositorio.save(personajePelicula53);
			personajePeliculaRepositorio.save(personajePelicula54);
			personajePeliculaRepositorio.save(personajePelicula55);
			personajePeliculaRepositorio.save(personajePelicula56);
			personajePeliculaRepositorio.save(personajePelicula57);
			personajePeliculaRepositorio.save(personajePelicula58);
			personajePeliculaRepositorio.save(personajePelicula59);
			personajePeliculaRepositorio.save(personajePelicula60);
			personajePeliculaRepositorio.save(personajePelicula61);
			personajePeliculaRepositorio.save(personajePelicula62);
			personajePeliculaRepositorio.save(personajePelicula63);
			personajePeliculaRepositorio.save(personajePelicula64);
			personajePeliculaRepositorio.save(personajePelicula65);
			personajePeliculaRepositorio.save(personajePelicula66);




			GeneroPelicula generoPelicula9=new GeneroPelicula(genero4, pelicula9);
			GeneroPelicula generoPelicula10=new GeneroPelicula(genero4, pelicula10);
			GeneroPelicula generoPelicula11=new GeneroPelicula(genero4, pelicula11);
			GeneroPelicula generoPelicula12=new GeneroPelicula(genero4, pelicula12);
			GeneroPelicula generoPelicula13=new GeneroPelicula(genero4, pelicula13);
			GeneroPelicula generoPelicula14=new GeneroPelicula(genero4, pelicula14);
			GeneroPelicula generoPelicula15=new GeneroPelicula(genero4, pelicula15);
			GeneroPelicula generoPelicula16=new GeneroPelicula(genero4, pelicula16);
			GeneroPelicula generoPelicula17=new GeneroPelicula(genero4, pelicula17);
			GeneroPelicula generoPelicula18=new GeneroPelicula(genero4, pelicula18);
			GeneroPelicula generoPelicula19=new GeneroPelicula(genero4, pelicula19);
			GeneroPelicula generoPelicula20=new GeneroPelicula(genero4, pelicula20);
			GeneroPelicula generoPelicula21=new GeneroPelicula(genero4, pelicula21);
			GeneroPelicula generoPelicula22=new GeneroPelicula(genero4, pelicula22);
			GeneroPelicula generoPelicula23=new GeneroPelicula(genero4, pelicula23);
			GeneroPelicula generoPelicula24=new GeneroPelicula(genero4, pelicula24);
			GeneroPelicula generoPelicula25=new GeneroPelicula(genero4, pelicula25);
			GeneroPelicula generoPelicula26=new GeneroPelicula(genero4, pelicula26);
			GeneroPelicula generoPelicula27=new GeneroPelicula(genero4, pelicula27);
			GeneroPelicula generoPelicula28=new GeneroPelicula(genero4, pelicula28);
			GeneroPelicula generoPelicula29=new GeneroPelicula(genero4, pelicula29);
			GeneroPelicula generoPelicula30=new GeneroPelicula(genero4, pelicula30);
			GeneroPelicula generoPelicula31=new GeneroPelicula(genero4, pelicula31);
			GeneroPelicula generoPelicula32=new GeneroPelicula(genero4, pelicula32);
			GeneroPelicula generoPelicula33=new GeneroPelicula(genero4, pelicula33);
			GeneroPelicula generoPelicula34=new GeneroPelicula(genero4, pelicula34);
			GeneroPelicula generoPelicula35=new GeneroPelicula(genero4, pelicula35);
			GeneroPelicula generoPelicula36=new GeneroPelicula(genero4, pelicula36);
			GeneroPelicula generoPelicula37=new GeneroPelicula(genero4, pelicula37);
			GeneroPelicula generoPelicula38=new GeneroPelicula(genero4, pelicula38);
			GeneroPelicula generoPelicula39=new GeneroPelicula(genero4, pelicula39);
			GeneroPelicula generoPelicula40=new GeneroPelicula(genero4, pelicula40);
			GeneroPelicula generoPelicula41=new GeneroPelicula(genero4, pelicula41);
			GeneroPelicula generoPelicula42=new GeneroPelicula(genero4, pelicula42);
			GeneroPelicula generoPelicula43=new GeneroPelicula(genero4, pelicula43);
			GeneroPelicula generoPelicula44=new GeneroPelicula(genero4, pelicula44);
			GeneroPelicula generoPelicula45=new GeneroPelicula(genero4, pelicula45);
			GeneroPelicula generoPelicula46=new GeneroPelicula(genero4, pelicula46);
			GeneroPelicula generoPelicula47=new GeneroPelicula(genero4, pelicula47);
			GeneroPelicula generoPelicula48=new GeneroPelicula(genero4, pelicula48);
			GeneroPelicula generoPelicula49=new GeneroPelicula(genero4, pelicula49);
			GeneroPelicula generoPelicula50=new GeneroPelicula(genero4, pelicula50);
			GeneroPelicula generoPelicula51=new GeneroPelicula(genero4, pelicula51);
			GeneroPelicula generoPelicula52=new GeneroPelicula(genero4, pelicula52);
			GeneroPelicula generoPelicula53=new GeneroPelicula(genero4, pelicula53);
			GeneroPelicula generoPelicula54=new GeneroPelicula(genero4, pelicula54);
			GeneroPelicula generoPelicula55=new GeneroPelicula(genero4, pelicula55);
			GeneroPelicula generoPelicula56=new GeneroPelicula(genero4, pelicula56);
			GeneroPelicula generoPelicula57=new GeneroPelicula(genero4, pelicula57);
			GeneroPelicula generoPelicula58=new GeneroPelicula(genero4, pelicula58);
			GeneroPelicula generoPelicula59=new GeneroPelicula(genero4, pelicula59);
			GeneroPelicula generoPelicula60=new GeneroPelicula(genero4, pelicula60);
			GeneroPelicula generoPelicula61=new GeneroPelicula(genero4, pelicula61);
			GeneroPelicula generoPelicula62=new GeneroPelicula(genero4, pelicula62);
			GeneroPelicula generoPelicula63=new GeneroPelicula(genero4, pelicula63);
			GeneroPelicula generoPelicula64=new GeneroPelicula(genero4, pelicula64);
			GeneroPelicula generoPelicula65=new GeneroPelicula(genero4, pelicula65);
			GeneroPelicula generoPelicula66=new GeneroPelicula(genero4, pelicula66);
			GeneroPelicula generoPelicula67=new GeneroPelicula(genero4, pelicula67);
			GeneroPelicula generoPelicula68=new GeneroPelicula(genero4, pelicula68);
			GeneroPelicula generoPelicula69=new GeneroPelicula(genero4, pelicula69);
			GeneroPelicula generoPelicula70=new GeneroPelicula(genero9, pelicula9);
			GeneroPelicula generoPelicula71=new GeneroPelicula(genero9, pelicula10);
			GeneroPelicula generoPelicula72=new GeneroPelicula(genero9, pelicula12);
			GeneroPelicula generoPelicula73=new GeneroPelicula(genero9, pelicula18);
			GeneroPelicula generoPelicula74=new GeneroPelicula(genero9, pelicula19);
			GeneroPelicula generoPelicula75=new GeneroPelicula(genero9, pelicula21);
			GeneroPelicula generoPelicula76=new GeneroPelicula(genero9, pelicula22);
			GeneroPelicula generoPelicula77=new GeneroPelicula(genero9, pelicula29);
			GeneroPelicula generoPelicula78=new GeneroPelicula(genero9, pelicula31);
			GeneroPelicula generoPelicula79=new GeneroPelicula(genero9, pelicula33);
			GeneroPelicula generoPelicula80=new GeneroPelicula(genero9, pelicula34);
			GeneroPelicula generoPelicula81=new GeneroPelicula(genero9, pelicula48);
			GeneroPelicula generoPelicula82=new GeneroPelicula(genero8, pelicula9);
			GeneroPelicula generoPelicula83=new GeneroPelicula(genero8, pelicula11);
			GeneroPelicula generoPelicula84=new GeneroPelicula(genero8, pelicula13);
			GeneroPelicula generoPelicula85=new GeneroPelicula(genero8, pelicula16);
			GeneroPelicula generoPelicula86=new GeneroPelicula(genero8, pelicula21);
			GeneroPelicula generoPelicula87=new GeneroPelicula(genero8, pelicula23);
			GeneroPelicula generoPelicula88=new GeneroPelicula(genero8, pelicula26);
			GeneroPelicula generoPelicula89=new GeneroPelicula(genero8, pelicula28);
			GeneroPelicula generoPelicula90=new GeneroPelicula(genero8, pelicula34);
			GeneroPelicula generoPelicula91=new GeneroPelicula(genero8, pelicula36);
			GeneroPelicula generoPelicula92=new GeneroPelicula(genero8, pelicula38);
			GeneroPelicula generoPelicula93=new GeneroPelicula(genero8, pelicula43);
			GeneroPelicula generoPelicula94=new GeneroPelicula(genero8, pelicula51);
			GeneroPelicula generoPelicula95=new GeneroPelicula(genero8, pelicula56);
			GeneroPelicula generoPelicula96=new GeneroPelicula(genero8, pelicula65);
			GeneroPelicula generoPelicula97=new GeneroPelicula(genero8, pelicula68);
			GeneroPelicula generoPelicula98=new GeneroPelicula(genero8, pelicula69);
			GeneroPelicula generoPelicula100=new GeneroPelicula(genero5, pelicula10);
			GeneroPelicula generoPelicula101=new GeneroPelicula(genero5, pelicula11);
			GeneroPelicula generoPelicula102=new GeneroPelicula(genero5, pelicula12);
			GeneroPelicula generoPelicula104=new GeneroPelicula(genero5, pelicula14);
			GeneroPelicula generoPelicula105=new GeneroPelicula(genero5, pelicula15);
			GeneroPelicula generoPelicula106=new GeneroPelicula(genero5, pelicula16);
			GeneroPelicula generoPelicula107=new GeneroPelicula(genero5, pelicula17);
			GeneroPelicula generoPelicula108=new GeneroPelicula(genero5, pelicula18);
			GeneroPelicula generoPelicula109=new GeneroPelicula(genero5, pelicula19);
			GeneroPelicula generoPelicula110=new GeneroPelicula(genero5, pelicula20);
			GeneroPelicula generoPelicula111=new GeneroPelicula(genero5, pelicula21);
			GeneroPelicula generoPelicula112=new GeneroPelicula(genero5, pelicula22);
			GeneroPelicula generoPelicula114=new GeneroPelicula(genero5, pelicula24);
			GeneroPelicula generoPelicula115=new GeneroPelicula(genero5, pelicula25);
			GeneroPelicula generoPelicula117=new GeneroPelicula(genero5, pelicula27);
			GeneroPelicula generoPelicula119=new GeneroPelicula(genero5, pelicula29);
			GeneroPelicula generoPelicula120=new GeneroPelicula(genero5, pelicula30);
			GeneroPelicula generoPelicula121=new GeneroPelicula(genero5, pelicula31);
			GeneroPelicula generoPelicula122=new GeneroPelicula(genero5, pelicula32);
			GeneroPelicula generoPelicula123=new GeneroPelicula(genero5, pelicula33);
			GeneroPelicula generoPelicula125=new GeneroPelicula(genero5, pelicula35);
			GeneroPelicula generoPelicula126=new GeneroPelicula(genero5, pelicula36);
			GeneroPelicula generoPelicula127=new GeneroPelicula(genero5, pelicula37);
			GeneroPelicula generoPelicula128=new GeneroPelicula(genero5, pelicula38);
			GeneroPelicula generoPelicula129=new GeneroPelicula(genero5, pelicula39);
			GeneroPelicula generoPelicula130=new GeneroPelicula(genero5, pelicula40);
			GeneroPelicula generoPelicula131=new GeneroPelicula(genero5, pelicula41);
			GeneroPelicula generoPelicula132=new GeneroPelicula(genero5, pelicula42);
			GeneroPelicula generoPelicula133=new GeneroPelicula(genero5, pelicula43);
			GeneroPelicula generoPelicula134=new GeneroPelicula(genero5, pelicula44);
			GeneroPelicula generoPelicula135=new GeneroPelicula(genero5, pelicula45);
			GeneroPelicula generoPelicula136=new GeneroPelicula(genero5, pelicula46);
			GeneroPelicula generoPelicula137=new GeneroPelicula(genero5, pelicula47);
			GeneroPelicula generoPelicula138=new GeneroPelicula(genero5, pelicula48);
			GeneroPelicula generoPelicula139=new GeneroPelicula(genero5, pelicula49);
			GeneroPelicula generoPelicula140=new GeneroPelicula(genero5, pelicula50);
			GeneroPelicula generoPelicula141=new GeneroPelicula(genero5, pelicula51);
			GeneroPelicula generoPelicula142=new GeneroPelicula(genero5, pelicula52);
			GeneroPelicula generoPelicula143=new GeneroPelicula(genero5, pelicula53);
			GeneroPelicula generoPelicula144=new GeneroPelicula(genero5, pelicula54);
			GeneroPelicula generoPelicula145=new GeneroPelicula(genero5, pelicula55);
			GeneroPelicula generoPelicula147=new GeneroPelicula(genero5, pelicula57);
			GeneroPelicula generoPelicula148=new GeneroPelicula(genero5, pelicula58);
			GeneroPelicula generoPelicula149=new GeneroPelicula(genero5, pelicula59);
			GeneroPelicula generoPelicula150=new GeneroPelicula(genero5, pelicula60);
			GeneroPelicula generoPelicula151=new GeneroPelicula(genero5, pelicula61);
			GeneroPelicula generoPelicula152=new GeneroPelicula(genero5, pelicula62);
			GeneroPelicula generoPelicula153=new GeneroPelicula(genero5, pelicula63);
			GeneroPelicula generoPelicula154=new GeneroPelicula(genero5, pelicula64);
			GeneroPelicula generoPelicula155=new GeneroPelicula(genero5, pelicula65);
			GeneroPelicula generoPelicula156=new GeneroPelicula(genero5, pelicula66);
			GeneroPelicula generoPelicula157=new GeneroPelicula(genero5, pelicula67);
			GeneroPelicula generoPelicula158=new GeneroPelicula(genero7, pelicula68);
			GeneroPelicula generoPelicula164=new GeneroPelicula(genero6, pelicula14);
			GeneroPelicula generoPelicula165=new GeneroPelicula(genero6, pelicula15);
			GeneroPelicula generoPelicula167=new GeneroPelicula(genero6, pelicula17);
			GeneroPelicula generoPelicula174=new GeneroPelicula(genero6, pelicula24);
			GeneroPelicula generoPelicula177=new GeneroPelicula(genero6, pelicula27);
			GeneroPelicula generoPelicula180=new GeneroPelicula(genero6, pelicula30);
			GeneroPelicula generoPelicula182=new GeneroPelicula(genero6, pelicula32);
			GeneroPelicula generoPelicula185=new GeneroPelicula(genero6, pelicula35);
			GeneroPelicula generoPelicula187=new GeneroPelicula(genero6, pelicula37);
			GeneroPelicula generoPelicula189=new GeneroPelicula(genero6, pelicula39);
			GeneroPelicula generoPelicula191=new GeneroPelicula(genero6, pelicula41);
			GeneroPelicula generoPelicula192=new GeneroPelicula(genero6, pelicula42);
			GeneroPelicula generoPelicula194=new GeneroPelicula(genero6, pelicula44);
			GeneroPelicula generoPelicula195=new GeneroPelicula(genero6, pelicula45);
			GeneroPelicula generoPelicula196=new GeneroPelicula(genero6, pelicula46);
			GeneroPelicula generoPelicula199=new GeneroPelicula(genero6, pelicula49);
			GeneroPelicula generoPelicula200=new GeneroPelicula(genero6, pelicula50);
			GeneroPelicula generoPelicula202=new GeneroPelicula(genero6, pelicula52);
			GeneroPelicula generoPelicula203=new GeneroPelicula(genero6, pelicula53);
			GeneroPelicula generoPelicula204=new GeneroPelicula(genero6, pelicula54);
			GeneroPelicula generoPelicula205=new GeneroPelicula(genero6, pelicula55);
			GeneroPelicula generoPelicula206=new GeneroPelicula(genero6, pelicula56);
			GeneroPelicula generoPelicula207=new GeneroPelicula(genero6, pelicula57);
			GeneroPelicula generoPelicula208=new GeneroPelicula(genero6, pelicula58);
			GeneroPelicula generoPelicula209=new GeneroPelicula(genero6, pelicula59);
			GeneroPelicula generoPelicula211=new GeneroPelicula(genero6, pelicula61);
			GeneroPelicula generoPelicula212=new GeneroPelicula(genero6, pelicula62);
			GeneroPelicula generoPelicula213=new GeneroPelicula(genero6, pelicula63);
			GeneroPelicula generoPelicula214=new GeneroPelicula(genero6, pelicula64);
			GeneroPelicula generoPelicula216=new GeneroPelicula(genero6, pelicula66);
			GeneroPelicula generoPelicula218=new GeneroPelicula(genero6, pelicula68);
			GeneroPelicula generoPelicula219=new GeneroPelicula(genero6, pelicula69);
			GeneroPelicula generoPelicula231=new GeneroPelicula(genero2, pelicula20);
			GeneroPelicula generoPelicula251=new GeneroPelicula(genero2, pelicula40);
			GeneroPelicula generoPelicula258=new GeneroPelicula(genero2, pelicula47);
			GeneroPelicula generoPelicula271=new GeneroPelicula(genero2, pelicula60);
			GeneroPelicula generoPelicula275=new GeneroPelicula(genero1, pelicula13);
			GeneroPelicula generoPelicula285=new GeneroPelicula(genero1, pelicula23);
			GeneroPelicula generoPelicula288=new GeneroPelicula(genero1, pelicula26);
			GeneroPelicula generoPelicula290=new GeneroPelicula(genero1, pelicula28);
			GeneroPelicula generoPelicula291=new GeneroPelicula(genero3, pelicula25);
			GeneroPelicula generoPelicula292=new GeneroPelicula(genero4, pelicula1);
			GeneroPelicula generoPelicula293=new GeneroPelicula(genero5, pelicula1);
			GeneroPelicula generoPelicula294=new GeneroPelicula(genero9, pelicula1);
			GeneroPelicula generoPelicula295=new GeneroPelicula(genero4, pelicula5);
			GeneroPelicula generoPelicula296=new GeneroPelicula(genero8, pelicula5);
			GeneroPelicula generoPelicula297=new GeneroPelicula(genero9, pelicula5);
			GeneroPelicula generoPelicula298=new GeneroPelicula(genero1, pelicula6);
			GeneroPelicula generoPelicula299=new GeneroPelicula(genero4, pelicula6);
			GeneroPelicula generoPelicula300=new GeneroPelicula(genero8, pelicula6);
			GeneroPelicula generoPelicula301=new GeneroPelicula(genero4, pelicula7);
			GeneroPelicula generoPelicula302=new GeneroPelicula(genero6, pelicula7);
			GeneroPelicula generoPelicula303=new GeneroPelicula(genero8, pelicula7);
			GeneroPelicula generoPelicula304=new GeneroPelicula(genero1, pelicula8);
			GeneroPelicula generoPelicula305=new GeneroPelicula(genero4, pelicula8);
			GeneroPelicula generoPelicula306=new GeneroPelicula(genero8, pelicula8);
			generoPeliculaRepositorio.save(generoPelicula9);
			generoPeliculaRepositorio.save(generoPelicula10);
			generoPeliculaRepositorio.save(generoPelicula11);
			generoPeliculaRepositorio.save(generoPelicula12);
			generoPeliculaRepositorio.save(generoPelicula13);
			generoPeliculaRepositorio.save(generoPelicula14);
			generoPeliculaRepositorio.save(generoPelicula15);
			generoPeliculaRepositorio.save(generoPelicula16);
			generoPeliculaRepositorio.save(generoPelicula17);
			generoPeliculaRepositorio.save(generoPelicula18);
			generoPeliculaRepositorio.save(generoPelicula19);
			generoPeliculaRepositorio.save(generoPelicula20);
			generoPeliculaRepositorio.save(generoPelicula21);
			generoPeliculaRepositorio.save(generoPelicula22);
			generoPeliculaRepositorio.save(generoPelicula23);
			generoPeliculaRepositorio.save(generoPelicula24);
			generoPeliculaRepositorio.save(generoPelicula25);
			generoPeliculaRepositorio.save(generoPelicula26);
			generoPeliculaRepositorio.save(generoPelicula27);
			generoPeliculaRepositorio.save(generoPelicula28);
			generoPeliculaRepositorio.save(generoPelicula29);
			generoPeliculaRepositorio.save(generoPelicula30);
			generoPeliculaRepositorio.save(generoPelicula31);
			generoPeliculaRepositorio.save(generoPelicula32);
			generoPeliculaRepositorio.save(generoPelicula33);
			generoPeliculaRepositorio.save(generoPelicula34);
			generoPeliculaRepositorio.save(generoPelicula35);
			generoPeliculaRepositorio.save(generoPelicula36);
			generoPeliculaRepositorio.save(generoPelicula37);
			generoPeliculaRepositorio.save(generoPelicula38);
			generoPeliculaRepositorio.save(generoPelicula39);
			generoPeliculaRepositorio.save(generoPelicula40);
			generoPeliculaRepositorio.save(generoPelicula41);
			generoPeliculaRepositorio.save(generoPelicula42);
			generoPeliculaRepositorio.save(generoPelicula43);
			generoPeliculaRepositorio.save(generoPelicula44);
			generoPeliculaRepositorio.save(generoPelicula45);
			generoPeliculaRepositorio.save(generoPelicula46);
			generoPeliculaRepositorio.save(generoPelicula47);
			generoPeliculaRepositorio.save(generoPelicula48);
			generoPeliculaRepositorio.save(generoPelicula49);
			generoPeliculaRepositorio.save(generoPelicula50);
			generoPeliculaRepositorio.save(generoPelicula51);
			generoPeliculaRepositorio.save(generoPelicula52);
			generoPeliculaRepositorio.save(generoPelicula53);
			generoPeliculaRepositorio.save(generoPelicula54);
			generoPeliculaRepositorio.save(generoPelicula55);
			generoPeliculaRepositorio.save(generoPelicula56);
			generoPeliculaRepositorio.save(generoPelicula57);
			generoPeliculaRepositorio.save(generoPelicula58);
			generoPeliculaRepositorio.save(generoPelicula59);
			generoPeliculaRepositorio.save(generoPelicula60);
			generoPeliculaRepositorio.save(generoPelicula61);
			generoPeliculaRepositorio.save(generoPelicula62);
			generoPeliculaRepositorio.save(generoPelicula63);
			generoPeliculaRepositorio.save(generoPelicula64);
			generoPeliculaRepositorio.save(generoPelicula65);
			generoPeliculaRepositorio.save(generoPelicula66);
			generoPeliculaRepositorio.save(generoPelicula67);
			generoPeliculaRepositorio.save(generoPelicula68);
			generoPeliculaRepositorio.save(generoPelicula69);
			generoPeliculaRepositorio.save(generoPelicula70);
			generoPeliculaRepositorio.save(generoPelicula71);
			generoPeliculaRepositorio.save(generoPelicula72);
			generoPeliculaRepositorio.save(generoPelicula73);
			generoPeliculaRepositorio.save(generoPelicula74);
			generoPeliculaRepositorio.save(generoPelicula75);
			generoPeliculaRepositorio.save(generoPelicula76);
			generoPeliculaRepositorio.save(generoPelicula77);
			generoPeliculaRepositorio.save(generoPelicula78);
			generoPeliculaRepositorio.save(generoPelicula79);
			generoPeliculaRepositorio.save(generoPelicula80);
			generoPeliculaRepositorio.save(generoPelicula81);
			generoPeliculaRepositorio.save(generoPelicula82);
			generoPeliculaRepositorio.save(generoPelicula83);
			generoPeliculaRepositorio.save(generoPelicula84);
			generoPeliculaRepositorio.save(generoPelicula85);
			generoPeliculaRepositorio.save(generoPelicula86);
			generoPeliculaRepositorio.save(generoPelicula87);
			generoPeliculaRepositorio.save(generoPelicula88);
			generoPeliculaRepositorio.save(generoPelicula89);
			generoPeliculaRepositorio.save(generoPelicula90);
			generoPeliculaRepositorio.save(generoPelicula91);
			generoPeliculaRepositorio.save(generoPelicula92);
			generoPeliculaRepositorio.save(generoPelicula93);
			generoPeliculaRepositorio.save(generoPelicula94);
			generoPeliculaRepositorio.save(generoPelicula95);
			generoPeliculaRepositorio.save(generoPelicula96);
			generoPeliculaRepositorio.save(generoPelicula97);
			generoPeliculaRepositorio.save(generoPelicula98);
			generoPeliculaRepositorio.save(generoPelicula100);
			generoPeliculaRepositorio.save(generoPelicula101);
			generoPeliculaRepositorio.save(generoPelicula102);
			generoPeliculaRepositorio.save(generoPelicula104);
			generoPeliculaRepositorio.save(generoPelicula105);
			generoPeliculaRepositorio.save(generoPelicula106);
			generoPeliculaRepositorio.save(generoPelicula107);
			generoPeliculaRepositorio.save(generoPelicula108);
			generoPeliculaRepositorio.save(generoPelicula109);
			generoPeliculaRepositorio.save(generoPelicula110);
			generoPeliculaRepositorio.save(generoPelicula111);
			generoPeliculaRepositorio.save(generoPelicula112);
			generoPeliculaRepositorio.save(generoPelicula114);
			generoPeliculaRepositorio.save(generoPelicula115);
			generoPeliculaRepositorio.save(generoPelicula117);
			generoPeliculaRepositorio.save(generoPelicula119);
			generoPeliculaRepositorio.save(generoPelicula120);
			generoPeliculaRepositorio.save(generoPelicula121);
			generoPeliculaRepositorio.save(generoPelicula122);
			generoPeliculaRepositorio.save(generoPelicula123);
			generoPeliculaRepositorio.save(generoPelicula125);
			generoPeliculaRepositorio.save(generoPelicula126);
			generoPeliculaRepositorio.save(generoPelicula127);
			generoPeliculaRepositorio.save(generoPelicula128);
			generoPeliculaRepositorio.save(generoPelicula129);
			generoPeliculaRepositorio.save(generoPelicula130);
			generoPeliculaRepositorio.save(generoPelicula131);
			generoPeliculaRepositorio.save(generoPelicula132);
			generoPeliculaRepositorio.save(generoPelicula133);
			generoPeliculaRepositorio.save(generoPelicula134);
			generoPeliculaRepositorio.save(generoPelicula135);
			generoPeliculaRepositorio.save(generoPelicula136);
			generoPeliculaRepositorio.save(generoPelicula137);
			generoPeliculaRepositorio.save(generoPelicula138);
			generoPeliculaRepositorio.save(generoPelicula139);
			generoPeliculaRepositorio.save(generoPelicula140);
			generoPeliculaRepositorio.save(generoPelicula141);
			generoPeliculaRepositorio.save(generoPelicula142);
			generoPeliculaRepositorio.save(generoPelicula143);
			generoPeliculaRepositorio.save(generoPelicula144);
			generoPeliculaRepositorio.save(generoPelicula145);
			generoPeliculaRepositorio.save(generoPelicula147);
			generoPeliculaRepositorio.save(generoPelicula148);
			generoPeliculaRepositorio.save(generoPelicula149);
			generoPeliculaRepositorio.save(generoPelicula150);
			generoPeliculaRepositorio.save(generoPelicula151);
			generoPeliculaRepositorio.save(generoPelicula152);
			generoPeliculaRepositorio.save(generoPelicula153);
			generoPeliculaRepositorio.save(generoPelicula154);
			generoPeliculaRepositorio.save(generoPelicula155);
			generoPeliculaRepositorio.save(generoPelicula156);
			generoPeliculaRepositorio.save(generoPelicula157);
			generoPeliculaRepositorio.save(generoPelicula158);
			generoPeliculaRepositorio.save(generoPelicula164);
			generoPeliculaRepositorio.save(generoPelicula165);
			generoPeliculaRepositorio.save(generoPelicula167);
			generoPeliculaRepositorio.save(generoPelicula174);
			generoPeliculaRepositorio.save(generoPelicula177);
			generoPeliculaRepositorio.save(generoPelicula180);
			generoPeliculaRepositorio.save(generoPelicula182);
			generoPeliculaRepositorio.save(generoPelicula185);
			generoPeliculaRepositorio.save(generoPelicula187);
			generoPeliculaRepositorio.save(generoPelicula189);
			generoPeliculaRepositorio.save(generoPelicula191);
			generoPeliculaRepositorio.save(generoPelicula192);
			generoPeliculaRepositorio.save(generoPelicula194);
			generoPeliculaRepositorio.save(generoPelicula195);
			generoPeliculaRepositorio.save(generoPelicula196);
			generoPeliculaRepositorio.save(generoPelicula199);
			generoPeliculaRepositorio.save(generoPelicula200);
			generoPeliculaRepositorio.save(generoPelicula202);
			generoPeliculaRepositorio.save(generoPelicula203);
			generoPeliculaRepositorio.save(generoPelicula204);
			generoPeliculaRepositorio.save(generoPelicula205);
			generoPeliculaRepositorio.save(generoPelicula206);
			generoPeliculaRepositorio.save(generoPelicula207);
			generoPeliculaRepositorio.save(generoPelicula208);
			generoPeliculaRepositorio.save(generoPelicula209);
			generoPeliculaRepositorio.save(generoPelicula211);
			generoPeliculaRepositorio.save(generoPelicula212);
			generoPeliculaRepositorio.save(generoPelicula213);
			generoPeliculaRepositorio.save(generoPelicula214);
			generoPeliculaRepositorio.save(generoPelicula216);
			generoPeliculaRepositorio.save(generoPelicula218);
			generoPeliculaRepositorio.save(generoPelicula219);
			generoPeliculaRepositorio.save(generoPelicula231);
			generoPeliculaRepositorio.save(generoPelicula251);
			generoPeliculaRepositorio.save(generoPelicula258);
			generoPeliculaRepositorio.save(generoPelicula271);
			generoPeliculaRepositorio.save(generoPelicula275);
			generoPeliculaRepositorio.save(generoPelicula285);
			generoPeliculaRepositorio.save(generoPelicula288);
			generoPeliculaRepositorio.save(generoPelicula290);
			generoPeliculaRepositorio.save(generoPelicula291);
			generoPeliculaRepositorio.save(generoPelicula292);
			generoPeliculaRepositorio.save(generoPelicula293);
			generoPeliculaRepositorio.save(generoPelicula294);
			generoPeliculaRepositorio.save(generoPelicula295);
			generoPeliculaRepositorio.save(generoPelicula296);
			generoPeliculaRepositorio.save(generoPelicula297);
			generoPeliculaRepositorio.save(generoPelicula298);
			generoPeliculaRepositorio.save(generoPelicula299);
			generoPeliculaRepositorio.save(generoPelicula300);
			generoPeliculaRepositorio.save(generoPelicula301);
			generoPeliculaRepositorio.save(generoPelicula302);
			generoPeliculaRepositorio.save(generoPelicula303);
			generoPeliculaRepositorio.save(generoPelicula304);
			generoPeliculaRepositorio.save(generoPelicula305);
			generoPeliculaRepositorio.save(generoPelicula306);
















		};
	}

}
